/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DataSourceSheetTypeEnum,
    DuplicateFields,
    ImportStepEnum,
    Metadata,
    ProjectDetails,
    SessionMappingStatus,
    SessionValidationStatus,
    SourceDataHeader,
} from './';

/**
 * @export
 * @interface BaseImportData
 */
export interface BaseImportData {
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    redcapToken: string;
    /**
     * @type {ImportStepEnum}
     * @memberof BaseImportData
     */
    currentStep: ImportStepEnum;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    recordIdField: string;
    /**
     * @type {ProjectDetails}
     * @memberof BaseImportData
     */
    projectDetails: ProjectDetails;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    sourceName: string;
    /**
     * @type {Array<SourceDataHeader>}
     * @memberof BaseImportData
     */
    sourceDataHeaders: Array<SourceDataHeader>;
    /**
     * @type {Array<DuplicateFields>}
     * @memberof BaseImportData
     */
    duplicateSourceFields: Array<DuplicateFields>;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    checkboxDelimiter: string;
    /**
     * @type {Array<string>}
     * @memberof BaseImportData
     */
    metadataForms: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof BaseImportData
     */
    metadataHeaders: Array<string>;
    /**
     * @type {Array<Metadata>}
     * @memberof BaseImportData
     */
    metadata: Array<Metadata>;
    /**
     * @type {DataSourceSheetTypeEnum}
     * @memberof BaseImportData
     */
    sheetType: DataSourceSheetTypeEnum;
    /**
     * @type {boolean}
     * @memberof BaseImportData
     */
    isMultiSheet: boolean;
    /**
     * @type {Array<string>}
     * @memberof BaseImportData
     */
    malformedSheets: Array<string>;
    /**
     * @type {boolean}
     * @memberof BaseImportData
     */
    confirmDeletions: boolean;
    /**
     * @type {SessionMappingStatus}
     * @memberof BaseImportData
     */
    mappingStatus: SessionMappingStatus;
    /**
     * @type {SessionValidationStatus}
     * @memberof BaseImportData
     */
    fieldValidationStatus: SessionValidationStatus;
    /**
     * @type {SessionValidationStatus}
     * @memberof BaseImportData
     */
    recordValidationStatus: SessionValidationStatus;
    /**
     * @type {SessionValidationStatus}
     * @memberof BaseImportData
     */
    mergeStatus: SessionValidationStatus;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    existingRecordsFetchedOn?: string;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    sheetJoinField?: string;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    encodedOn?: string;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    encodedDownloadOn?: string;
    /**
     * @type {string}
     * @memberof BaseImportData
     */
    encodedRcPushOn?: string;
}
