/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DuplicateResolveActionEnum,
} from './';

/**
 * @export
 * @interface DuplicateRecordCorrection
 */
export interface DuplicateRecordCorrection {
    /**
     * @type {string}
     * @memberof DuplicateRecordCorrection
     */
    _createdOn?: string;
    /**
     * @type {string}
     * @memberof DuplicateRecordCorrection
     */
    _modifiedOn?: string;
    /**
     * @type {string}
     * @memberof DuplicateRecordCorrection
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof DuplicateRecordCorrection
     */
    row: number;
    /**
     * @type {DuplicateResolveActionEnum}
     * @memberof DuplicateRecordCorrection
     */
    action: DuplicateResolveActionEnum;
    /**
     * @type {object}
     * @memberof DuplicateRecordCorrection
     */
    newIdentifier?: object;
}
