/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    UpdatedFieldValue,
} from './';

/**
 * @export
 * @interface EncodedRecords
 */
export interface EncodedRecords {
    /**
     * @type {boolean}
     * @memberof EncodedRecords
     */
    largeChangelogReport: boolean;
    /**
     * @type {number}
     * @memberof EncodedRecords
     */
    total: number;
    /**
     * @type {Array<string>}
     * @memberof EncodedRecords
     */
    recordHeaders: Array<string>;
    /**
     * @type {Array<object>}
     * @memberof EncodedRecords
     */
    records: Array<object>;
    /**
     * @type {Array<UpdatedFieldValue>}
     * @memberof EncodedRecords
     */
    updatedRecordItems?: Array<UpdatedFieldValue>;
    /**
     * @type {string}
     * @memberof EncodedRecords
     */
    recordIdField?: string;
}
