/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ExtractPermissibleValue
 */
export interface ExtractPermissibleValue {
    /**
     * @type {number}
     * @memberof ExtractPermissibleValue
     */
    id: number;
    /**
     * @type {number}
     * @memberof ExtractPermissibleValue
     */
    fieldId: number;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    topBraidId?: string;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    code?: string;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    label?: string;
    /**
     * @type {Array<string>}
     * @memberof ExtractPermissibleValue
     */
    synonyms?: Array<string>;
    /**
     * @type {number}
     * @memberof ExtractPermissibleValue
     */
    orderIndex?: number;
    /**
     * @type {number}
     * @memberof ExtractPermissibleValue
     */
    isDeleted?: number;
    /**
     * @type {number}
     * @memberof ExtractPermissibleValue
     */
    isVetted?: number;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    conceptId?: string;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    suggestedConceptId?: string;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    createdOn?: string;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    modifiedOn?: string;
    /**
     * @type {number}
     * @memberof ExtractPermissibleValue
     */
    modifiedBy?: number;
    /**
     * @type {string}
     * @memberof ExtractPermissibleValue
     */
    modifiedByEmail?: string;
    /**
     * @type {number}
     * @memberof ExtractPermissibleValue
     */
    isDisabled?: number;
}
