/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ExtractFieldSynonym
 */
export interface ExtractFieldSynonym {
    /**
     * @type {number}
     * @memberof ExtractFieldSynonym
     */
    id?: number;
    /**
     * @type {number}
     * @memberof ExtractFieldSynonym
     */
    fieldId?: number;
    /**
     * @type {string}
     * @memberof ExtractFieldSynonym
     */
    label: string;
    /**
     * @type {string}
     * @memberof ExtractFieldSynonym
     */
    createdOn?: string;
    /**
     * @type {number}
     * @memberof ExtractFieldSynonym
     */
    isVetted: number;
    /**
     * @type {string}
     * @memberof ExtractFieldSynonym
     */
    userId?: string;
    /**
     * @type {number}
     * @memberof ExtractFieldSynonym
     */
    isDeleted?: number;
    /**
     * @type {string}
     * @memberof ExtractFieldSynonym
     */
    modifiedOn?: string;
    /**
     * @type {string}
     * @memberof ExtractFieldSynonym
     */
    modifiedByEmail?: string;
}
