/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ExtractSessionInfo
 */
export interface ExtractSessionInfo {
    /**
     * @type {number}
     * @memberof ExtractSessionInfo
     */
    id?: number;
    /**
     * @type {number}
     * @memberof ExtractSessionInfo
     */
    sessionId?: number;
    /**
     * @type {string}
     * @memberof ExtractSessionInfo
     */
    infoKey?: string;
    /**
     * @type {string}
     * @memberof ExtractSessionInfo
     */
    infoValue?: string;
}
