/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ExtractFieldSynonym,
    ExtractOntologySource,
    ExtractPermissibleValue,
} from './';

/**
 * @export
 * @interface ExtractField
 */
export interface ExtractField {
    /**
     * @type {number}
     * @memberof ExtractField
     */
    id?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    conceptId?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    suggestedConceptId?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    projectId?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    topBraidId?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    observationGroupId?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    formName?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    formLabel?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    formId?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    formOrder?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    formIsRepeatable?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    formNameSuggestion?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    formFriendlyLabels?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    fieldOrder?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    name?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    label?: string;
    /**
     * @type {Array<string>}
     * @memberof ExtractField
     */
    synonyms?: Array<string>;
    /**
     * @type {Array<ExtractFieldSynonym>}
     * @memberof ExtractField
     */
    synonymsFull?: Array<ExtractFieldSynonym>;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    definition?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    dataType?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    dataFormat?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    note?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    identifier?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    required?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    alignment?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    annotation?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    priority?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    validationMin?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    validationMax?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    sectionHeader?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    matrixGroupName?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    matrixRanking?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    branchingLogic?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    questionNumber?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    calculationEquation?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    isVetted?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    needTerminologistReview?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    isPrivate?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    isDeleted?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    isDisabled?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    isRecordId?: number;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    isLocked?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    charColor?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    badgeColor?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    createdOn?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    modifiedOn?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    modifiedBy?: number;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    modifiedByEmail?: string;
    /**
     * @type {Array<ExtractPermissibleValue>}
     * @memberof ExtractField
     */
    permissibleValues?: Array<ExtractPermissibleValue>;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    permissibleValuesStr?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    status?: string;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    visibility?: string;
    /**
     * @type {boolean}
     * @memberof ExtractField
     */
    alreadyAdded?: boolean;
    /**
     * @type {boolean}
     * @memberof ExtractField
     */
    deprecatedConcept?: boolean;
    /**
     * @type {string}
     * @memberof ExtractField
     */
    firstPermissibleValue?: string;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    permissibleValuesCount?: number;
    /**
     * @type {Array<ExtractOntologySource>}
     * @memberof ExtractField
     */
    sources?: Array<ExtractOntologySource>;
    /**
     * @type {boolean}
     * @memberof ExtractField
     */
    isEngageField?: boolean;
    /**
     * @type {number}
     * @memberof ExtractField
     */
    fieldInstance?: number;
}
