/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SourceFieldCandidate,
} from './';

/**
 * @export
 * @interface FieldCandidatesResponseAllOfResult
 */
export interface FieldCandidatesResponseAllOfResult {
    /**
     * @type {number}
     * @memberof FieldCandidatesResponseAllOfResult
     */
    total?: number;
    /**
     * @type {SourceFieldCandidate}
     * @memberof FieldCandidatesResponseAllOfResult
     */
    candidate?: SourceFieldCandidate;
}
