/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AsyncTaskStatusEnum,
    AsyncTaskTypeEnum,
} from './';

/**
 * @export
 * @interface AsyncTaskRes
 */
export interface AsyncTaskRes {
    /**
     * @type {string}
     * @memberof AsyncTaskRes
     */
    taskId: string;
    /**
     * @type {AsyncTaskTypeEnum}
     * @memberof AsyncTaskRes
     */
    taskType: AsyncTaskTypeEnum;
    /**
     * @type {AsyncTaskStatusEnum}
     * @memberof AsyncTaskRes
     */
    status: AsyncTaskStatusEnum;
    /**
     * @type {object}
     * @memberof AsyncTaskRes
     */
    message?: object;
}
