/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BulkResolveMergeConflict
 */
export interface BulkResolveMergeConflict {
    /**
     * @type {string}
     * @memberof BulkResolveMergeConflict
     */
    projectUid: string;
    /**
     * @type {string}
     * @memberof BulkResolveMergeConflict
     */
    sessionUid: string;
    /**
     * @type {string}
     * @memberof BulkResolveMergeConflict
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof BulkResolveMergeConflict
     */
    row: number;
    /**
     * @type {string}
     * @memberof BulkResolveMergeConflict
     */
    identifierValue: string;
    /**
     * @type {string}
     * @memberof BulkResolveMergeConflict
     */
    valueType: BulkResolveMergeConflictValueTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum BulkResolveMergeConflictValueTypeEnum {
    SourceData = 'sourceData',
    Existing = 'existing'
}

