/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DestinationCandidate
 */
export interface DestinationCandidate {
    /**
     * @type {Array<string>}
     * @memberof DestinationCandidate
     */
    sheets: Array<string>;
    /**
     * @type {string}
     * @memberof DestinationCandidate
     */
    name: string;
    /**
     * @type {string}
     * @memberof DestinationCandidate
     */
    conceptId?: string;
    /**
     * @type {number}
     * @memberof DestinationCandidate
     */
    score: number;
}
