/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ExtractSessionInfo,
    RedcapInstance,
} from './';

/**
 * @export
 * @interface ExtractSession
 */
export interface ExtractSession {
    /**
     * @type {number}
     * @memberof ExtractSession
     */
    id: number;
    /**
     * @type {number}
     * @memberof ExtractSession
     */
    userId: number;
    /**
     * @type {string}
     * @memberof ExtractSession
     */
    openedOn: string;
    /**
     * @type {string}
     * @memberof ExtractSession
     */
    closedOn?: string;
    /**
     * @type {string}
     * @memberof ExtractSession
     */
    token?: string;
    /**
     * @type {number}
     * @memberof ExtractSession
     */
    redcapInstanceId: number;
    /**
     * @type {RedcapInstance}
     * @memberof ExtractSession
     */
    redcapInstance: RedcapInstance;
    /**
     * @type {Array<ExtractSessionInfo>}
     * @memberof ExtractSession
     */
    sessionInfo: Array<ExtractSessionInfo>;
    /**
     * @type {object}
     * @memberof ExtractSession
     */
    webSocket?: object;
}
