/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ExtractReleaseInfoSourceProjectCount,
} from './';

/**
 * @export
 * @interface ExtractReleaseInfoSourceProject
 */
export interface ExtractReleaseInfoSourceProject {
    /**
     * @type {number}
     * @memberof ExtractReleaseInfoSourceProject
     */
    id?: number;
    /**
     * @type {string}
     * @memberof ExtractReleaseInfoSourceProject
     */
    title?: string;
    /**
     * @type {string}
     * @memberof ExtractReleaseInfoSourceProject
     */
    description?: string;
    /**
     * @type {string}
     * @memberof ExtractReleaseInfoSourceProject
     */
    modifiedOn?: string;
    /**
     * @type {ExtractReleaseInfoSourceProjectCount}
     * @memberof ExtractReleaseInfoSourceProject
     */
    _count?: ExtractReleaseInfoSourceProjectCount;
}
