/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ExtractUser,
} from './';

/**
 * @export
 * @interface ExtractProject
 */
export interface ExtractProject {
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    _id: number;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    extractId: number;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    legacyExtractId: number;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    redcapUrl?: string;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    redcapId?: number;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    redcapToken?: string;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    title: string;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    description: string;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    purpose?: number;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    otherPurpose?: number;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    irbNumber?: string;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    inProduction: boolean;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    autonumEnabled: boolean;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    hasRepeatingInstruments: boolean;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    isLongitudinal: boolean;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    isArchived: boolean;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    createdOn?: string;
    /**
     * @type {ExtractUser}
     * @memberof ExtractProject
     */
    createdBy?: ExtractUser;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    importedOn?: string;
    /**
     * @type {ExtractUser}
     * @memberof ExtractProject
     */
    importedBy?: ExtractUser;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    modifiedOn?: string;
    /**
     * @type {ExtractUser}
     * @memberof ExtractProject
     */
    modifiedBy?: ExtractUser;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    publishedOn?: string;
    /**
     * @type {ExtractUser}
     * @memberof ExtractProject
     */
    publishedBy?: ExtractUser;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    isFrozen: number;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    frozenOn?: string;
    /**
     * @type {ExtractUser}
     * @memberof ExtractProject
     */
    frozenBy?: ExtractUser;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    isLocked: boolean;
    /**
     * @type {ExtractUser}
     * @memberof ExtractProject
     */
    lockedBy?: ExtractUser;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    revertedOn?: string;
    /**
     * @type {ExtractUser}
     * @memberof ExtractProject
     */
    revertedBy?: ExtractUser;
    /**
     * @type {Array<ExtractUser>}
     * @memberof ExtractProject
     */
    projectUsers?: Array<ExtractUser>;
    /**
     * @type {Array<ExtractUser>}
     * @memberof ExtractProject
     */
    projectManagers?: Array<ExtractUser>;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    formsCount: number;
    /**
     * @type {number}
     * @memberof ExtractProject
     */
    fieldsCount: number;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    lastSyncedOn: string;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    lastDataSyncAttempted?: string;
    /**
     * @type {string}
     * @memberof ExtractProject
     */
    lastDataSyncCompleted?: string;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    isTemporary: boolean;
    /**
     * @type {boolean}
     * @memberof ExtractProject
     */
    isTemplate: boolean;
}
