/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ExtractRole,
} from './';

/**
 * @export
 * @interface ExtractUser
 */
export interface ExtractUser {
    /**
     * @type {number}
     * @memberof ExtractUser
     */
    id: number;
    /**
     * @type {string}
     * @memberof ExtractUser
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof ExtractUser
     */
    lastName: string;
    /**
     * @type {string}
     * @memberof ExtractUser
     */
    login: string;
    /**
     * @type {string}
     * @memberof ExtractUser
     */
    email: string;
    /**
     * @type {string}
     * @memberof ExtractUser
     */
    ssoToken: string;
    /**
     * @type {string}
     * @memberof ExtractUser
     */
    refreshToken: string;
    /**
     * @type {ExtractRole}
     * @memberof ExtractUser
     */
    role: ExtractRole;
    /**
     * @type {ExtractRole}
     * @memberof ExtractUser
     */
    impersonationRole?: ExtractRole;
    /**
     * @type {string}
     * @memberof ExtractUser
     */
    redcapUrl: string;
    /**
     * @type {boolean}
     * @memberof ExtractUser
     */
    isLegacy?: boolean;
}
