/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ExtractReleaseInfoAcceptedFields,
    ExtractReleaseInfoDestinationProject,
    ExtractReleaseInfoInitiatingUser,
    ExtractReleaseInfoRecipients,
    ExtractReleaseInfoRecordRange,
    ExtractReleaseInfoSourceProject,
} from './';

/**
 * @export
 * @interface ExtractReleaseInfo
 */
export interface ExtractReleaseInfo {
    /**
     * @type {number}
     * @memberof ExtractReleaseInfo
     */
    releaseId?: number;
    /**
     * @type {ExtractReleaseInfoSourceProject}
     * @memberof ExtractReleaseInfo
     */
    sourceProject?: ExtractReleaseInfoSourceProject;
    /**
     * @type {Array<number>}
     * @memberof ExtractReleaseInfo
     */
    recordIds?: Array<number>;
    /**
     * @type {Array<ExtractReleaseInfoRecordRange>}
     * @memberof ExtractReleaseInfo
     */
    recordRange?: Array<ExtractReleaseInfoRecordRange>;
    /**
     * @type {ExtractReleaseInfoInitiatingUser}
     * @memberof ExtractReleaseInfo
     */
    initiatingUser?: ExtractReleaseInfoInitiatingUser;
    /**
     * @type {Array<ExtractReleaseInfoRecipients>}
     * @memberof ExtractReleaseInfo
     */
    recipients?: Array<ExtractReleaseInfoRecipients>;
    /**
     * @type {ExtractReleaseInfoDestinationProject}
     * @memberof ExtractReleaseInfo
     */
    destinationProject?: ExtractReleaseInfoDestinationProject;
    /**
     * @type {Array<ExtractReleaseInfoAcceptedFields>}
     * @memberof ExtractReleaseInfo
     */
    acceptedFields?: Array<ExtractReleaseInfoAcceptedFields>;
    /**
     * @type {Array<ExtractReleaseInfoAcceptedFields>}
     * @memberof ExtractReleaseInfo
     */
    pipingSnapshotFields?: Array<ExtractReleaseInfoAcceptedFields>;
    /**
     * @type {Array<string>}
     * @memberof ExtractReleaseInfo
     */
    mrns?: Array<string>;
}
