/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ValidationErrorTypeEnum,
    ValueValidationError,
} from './';

/**
 * @export
 * @interface FieldValidationError
 */
export interface FieldValidationError {
    /**
     * @type {string}
     * @memberof FieldValidationError
     */
    sheetName?: string;
    /**
     * @type {ValidationErrorTypeEnum}
     * @memberof FieldValidationError
     */
    errorType?: ValidationErrorTypeEnum;
    /**
     * @type {string}
     * @memberof FieldValidationError
     */
    fieldName?: string;
    /**
     * @type {string}
     * @memberof FieldValidationError
     */
    fieldType?: string;
    /**
     * @type {string}
     * @memberof FieldValidationError
     */
    conceptId?: string;
    /**
     * @type {boolean}
     * @memberof FieldValidationError
     */
    required?: boolean;
    /**
     * @type {string}
     * @memberof FieldValidationError
     */
    validationType?: string;
    /**
     * @type {string}
     * @memberof FieldValidationError
     */
    validationMin?: string;
    /**
     * @type {string}
     * @memberof FieldValidationError
     */
    validationMax?: string;
    /**
     * @type {Array<number>}
     * @memberof FieldValidationError
     */
    emptyRows?: Array<number>;
    /**
     * @type {Array<ValueValidationError>}
     * @memberof FieldValidationError
     */
    invalidValues?: Array<ValueValidationError>;
    /**
     * @type {number}
     * @memberof FieldValidationError
     */
    totalInvalid?: number;
    /**
     * @type {Array<string>}
     * @memberof FieldValidationError
     */
    errorMsgs?: Array<string>;
}
