/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MergeConflict,
    RepeatFormInstanceMapping,
} from './';

/**
 * @export
 * @interface IdentifierMergeConflict
 */
export interface IdentifierMergeConflict {
    /**
     * @type {string}
     * @memberof IdentifierMergeConflict
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof IdentifierMergeConflict
     */
    row: number;
    /**
     * @type {string}
     * @memberof IdentifierMergeConflict
     */
    identifierValue: string;
    /**
     * @type {object}
     * @memberof IdentifierMergeConflict
     */
    identifiers?: object;
    /**
     * @type {object}
     * @memberof IdentifierMergeConflict
     */
    record?: object;
    /**
     * @type {object}
     * @memberof IdentifierMergeConflict
     */
    fieldTypeMap?: object;
    /**
     * @type {Array<MergeConflict>}
     * @memberof IdentifierMergeConflict
     */
    conflicts: Array<MergeConflict>;
    /**
     * @type {Array<RepeatFormInstanceMapping>}
     * @memberof IdentifierMergeConflict
     */
    matchingRepeatInstances?: Array<RepeatFormInstanceMapping>;
    /**
     * @type {number}
     * @memberof IdentifierMergeConflict
     */
    totalFields?: number;
    /**
     * @type {Array<string>}
     * @memberof IdentifierMergeConflict
     */
    conflictFields: Array<string>;
    /**
     * @type {number}
     * @memberof IdentifierMergeConflict
     */
    totalConflicts?: number;
}
