/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface IdentifierWithMergeConflict
 */
export interface IdentifierWithMergeConflict {
    /**
     * @type {string}
     * @memberof IdentifierWithMergeConflict
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof IdentifierWithMergeConflict
     */
    row: number;
    /**
     * @type {string}
     * @memberof IdentifierWithMergeConflict
     */
    identifierValue: string;
    /**
     * @type {object}
     * @memberof IdentifierWithMergeConflict
     */
    identifierDict?: object;
}
