/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IgnoredSourceField,
} from './';

/**
 * @export
 * @interface IgnoredFieldsResponseAllOf
 */
export interface IgnoredFieldsResponseAllOf {
    /**
     * @type {Array<IgnoredSourceField>}
     * @memberof IgnoredFieldsResponseAllOf
     */
    result: Array<IgnoredSourceField>;
}
