/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    InconsistentFieldCorrection,
    InconsistentValue,
} from './';

/**
 * @export
 * @interface InconsistentField
 */
export interface InconsistentField {
    /**
     * @type {string}
     * @memberof InconsistentField
     */
    fieldName: string;
    /**
     * @type {number}
     * @memberof InconsistentField
     */
    valueCount: number;
    /**
     * @type {Array<InconsistentValue>}
     * @memberof InconsistentField
     */
    values?: Array<InconsistentValue>;
    /**
     * @type {InconsistentFieldCorrection}
     * @memberof InconsistentField
     */
    correction?: InconsistentFieldCorrection;
}
