/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InconsistentFieldCorrection
 */
export interface InconsistentFieldCorrection {
    /**
     * @type {string}
     * @memberof InconsistentFieldCorrection
     */
    _createdOn?: string;
    /**
     * @type {string}
     * @memberof InconsistentFieldCorrection
     */
    _modifiedOn?: string;
    /**
     * @type {number}
     * @memberof InconsistentFieldCorrection
     */
    row?: number;
    /**
     * @type {string}
     * @memberof InconsistentFieldCorrection
     */
    sheet: string;
    /**
     * @type {string}
     * @memberof InconsistentFieldCorrection
     */
    fieldName: string;
    /**
     * @type {string}
     * @memberof InconsistentFieldCorrection
     */
    conceptId?: string;
    /**
     * @type {Array<string>}
     * @memberof InconsistentFieldCorrection
     */
    original: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof InconsistentFieldCorrection
     */
    update?: Array<string>;
}
