/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface InconsistentConflictPayload
 */
export interface InconsistentConflictPayload {
    /**
     * @type {string}
     * @memberof InconsistentConflictPayload
     */
    identifierValue?: string;
    /**
     * @type {string}
     * @memberof InconsistentConflictPayload
     */
    sheetName?: string;
    /**
     * @type {number}
     * @memberof InconsistentConflictPayload
     */
    page?: number;
    /**
     * @type {number}
     * @memberof InconsistentConflictPayload
     */
    pageSize?: number;
    /**
     * @type {string}
     * @memberof InconsistentConflictPayload
     */
    searchTerm?: string;
    /**
     * @type {boolean}
     * @memberof InconsistentConflictPayload
     */
    conflictsOnly?: boolean;
}
