/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LinkedFieldValue,
} from './';

/**
 * @export
 * @interface LinkedField
 */
export interface LinkedField {
    /**
     * @type {string}
     * @memberof LinkedField
     */
    _id?: string;
    /**
     * @type {string}
     * @memberof LinkedField
     */
    _projectUid: string;
    /**
     * @type {string}
     * @memberof LinkedField
     */
    _sessionUid: string;
    /**
     * @type {string}
     * @memberof LinkedField
     */
    sheet: string;
    /**
     * @type {string}
     * @memberof LinkedField
     */
    fieldName: string;
    /**
     * @type {string}
     * @memberof LinkedField
     */
    conceptId?: string;
    /**
     * @type {Array<LinkedFieldValue>}
     * @memberof LinkedField
     */
    linkedValues?: Array<LinkedFieldValue>;
}
