/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RepeatingFormIdentifiers,
} from './';

/**
 * @export
 * @interface MergeSettings
 */
export interface MergeSettings {
    /**
     * @type {boolean}
     * @memberof MergeSettings
     */
    replaceBlankRc: boolean;
    /**
     * @type {Array<RepeatingFormIdentifiers>}
     * @memberof MergeSettings
     */
    reconciliationFields?: Array<RepeatingFormIdentifiers>;
    /**
     * @type {Array<string>}
     * @memberof MergeSettings
     */
    overrideValues: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof MergeSettings
     */
    overrideFields: Array<string>;
}
