/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MetadataOptionsDictionary,
} from './';

/**
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * @type {string}
     * @memberof Metadata
     */
    _id?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    _projectUid?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    fieldName: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    formName: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    conceptId?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    fieldType: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    fieldLabel: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    choicesCalculationsOrSliderLabels?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    textValidation?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    validationMin?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    validationMax?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    identifier?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    required?: string;
    /**
     * @type {number}
     * @memberof Metadata
     */
    totalOptions?: number;
    /**
     * @type {Array<MetadataOptionsDictionary>}
     * @memberof Metadata
     */
    optionsDictionary?: Array<MetadataOptionsDictionary>;
    /**
     * @type {string}
     * @memberof Metadata
     */
    sectionHeader?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    fieldNote?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    branchingLogic?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    alignment?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    questionNumber?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    matrixRanking?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    fieldAnnotation?: string;
    /**
     * @type {string}
     * @memberof Metadata
     */
    definition?: string;
}
