/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Metadata,
    MetadataResMappingsCounts,
} from './';

/**
 * @export
 * @interface MetadataRes
 */
export interface MetadataRes {
    /**
     * @type {number}
     * @memberof MetadataRes
     */
    total: number;
    /**
     * @type {number}
     * @memberof MetadataRes
     */
    totalPvs?: number;
    /**
     * @type {Array<Metadata>}
     * @memberof MetadataRes
     */
    data: Array<Metadata>;
    /**
     * @type {Array<MetadataResMappingsCounts>}
     * @memberof MetadataRes
     */
    mappingsCounts?: Array<MetadataResMappingsCounts>;
}
