/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CorrectionTypeEnum,
} from './';

/**
 * @export
 * @interface NewChangelogItem
 */
export interface NewChangelogItem {
    /**
     * @type {CorrectionTypeEnum}
     * @memberof NewChangelogItem
     */
    _type?: CorrectionTypeEnum;
    /**
     * @type {string}
     * @memberof NewChangelogItem
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof NewChangelogItem
     */
    row: number;
    /**
     * @type {string}
     * @memberof NewChangelogItem
     */
    identifierValue?: string;
    /**
     * @type {string}
     * @memberof NewChangelogItem
     */
    fieldName: string;
    /**
     * @type {string}
     * @memberof NewChangelogItem
     */
    conceptId?: string;
    /**
     * @type {string}
     * @memberof NewChangelogItem
     */
    original: string;
    /**
     * @type {string}
     * @memberof NewChangelogItem
     */
    update?: string;
    /**
     * @type {string}
     * @memberof NewChangelogItem
     */
    notes?: string;
}
