/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NewFormattedItemMsg
 */
export interface NewFormattedItemMsg {
    /**
     * @type {string}
     * @memberof NewFormattedItemMsg
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof NewFormattedItemMsg
     */
    row: number;
    /**
     * @type {string}
     * @memberof NewFormattedItemMsg
     */
    fieldName?: string;
    /**
     * @type {string}
     * @memberof NewFormattedItemMsg
     */
    message: string;
}
