/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Metadata,
} from './';

/**
 * @export
 * @interface NewFieldMapping
 */
export interface NewFieldMapping {
    /**
     * @type {string}
     * @memberof NewFieldMapping
     */
    _createdOn?: string;
    /**
     * @type {string}
     * @memberof NewFieldMapping
     */
    _modifiedOn?: string;
    /**
     * @type {boolean}
     * @memberof NewFieldMapping
     */
    ignored?: boolean;
    /**
     * @type {string}
     * @memberof NewFieldMapping
     */
    sheet: string;
    /**
     * @type {string}
     * @memberof NewFieldMapping
     */
    sourceFieldName: string;
    /**
     * @type {string}
     * @memberof NewFieldMapping
     */
    sourceConceptId?: string;
    /**
     * @type {string}
     * @memberof NewFieldMapping
     */
    destinationFieldName?: string;
    /**
     * @type {string}
     * @memberof NewFieldMapping
     */
    destinationConceptId?: string;
    /**
     * @type {Metadata}
     * @memberof NewFieldMapping
     */
    destinationField?: Metadata;
}
