/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MergeConflictCorrection,
} from './';

/**
 * @export
 * @interface NewMergeConflict
 */
export interface NewMergeConflict {
    /**
     * @type {string}
     * @memberof NewMergeConflict
     */
    sheet: string;
    /**
     * @type {string}
     * @memberof NewMergeConflict
     */
    identifierValue?: string;
    /**
     * @type {number}
     * @memberof NewMergeConflict
     */
    row: number;
    /**
     * @type {string}
     * @memberof NewMergeConflict
     */
    fieldName: string;
    /**
     * @type {string}
     * @memberof NewMergeConflict
     */
    conceptId?: string;
    /**
     * @type {boolean}
     * @memberof NewMergeConflict
     */
    isRepeatField: boolean;
    /**
     * @type {Array<string>}
     * @memberof NewMergeConflict
     */
    destinationValue: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof NewMergeConflict
     */
    sourceValue: Array<string>;
    /**
     * @type {MergeConflictCorrection}
     * @memberof NewMergeConflict
     */
    correction?: MergeConflictCorrection;
}
