/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NewRepeatFormInstanceMapping
 */
export interface NewRepeatFormInstanceMapping {
    /**
     * @type {string}
     * @memberof NewRepeatFormInstanceMapping
     */
    sheet?: string;
    /**
     * @type {string}
     * @memberof NewRepeatFormInstanceMapping
     */
    identifierValue?: string;
    /**
     * @type {number}
     * @memberof NewRepeatFormInstanceMapping
     */
    row?: number;
    /**
     * @type {string}
     * @memberof NewRepeatFormInstanceMapping
     */
    formName?: string;
    /**
     * @type {number}
     * @memberof NewRepeatFormInstanceMapping
     */
    repeatInstance?: number;
}
