/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    CorrectionTypeEnum,
} from './';

/**
 * @export
 * @interface NewValidationCorrection
 */
export interface NewValidationCorrection {
    /**
     * @type {string}
     * @memberof NewValidationCorrection
     */
    _createdOn?: string;
    /**
     * @type {string}
     * @memberof NewValidationCorrection
     */
    _modifiedOn?: string;
    /**
     * @type {CorrectionTypeEnum}
     * @memberof NewValidationCorrection
     */
    correctionType: CorrectionTypeEnum;
    /**
     * @type {string}
     * @memberof NewValidationCorrection
     */
    sheet: string;
    /**
     * @type {string}
     * @memberof NewValidationCorrection
     */
    fieldName: string;
    /**
     * @type {string}
     * @memberof NewValidationCorrection
     */
    conceptId?: string;
    /**
     * @type {string}
     * @memberof NewValidationCorrection
     */
    original: string;
    /**
     * @type {string}
     * @memberof NewValidationCorrection
     */
    update?: string;
}
