/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ProjectDetails
 */
export interface ProjectDetails {
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    _id?: string;
    /**
     * @type {number}
     * @memberof ProjectDetails
     */
    extractProjectId?: number;
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    redcapToken?: string;
    /**
     * @type {number}
     * @memberof ProjectDetails
     */
    redcapId?: number;
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    projectTitle?: string;
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    projectIrbNumber?: string;
    /**
     * @type {boolean}
     * @memberof ProjectDetails
     */
    recordAutoNumbering: boolean;
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    recordIdField: string;
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    recordIdPrefix?: string;
    /**
     * @type {Array<string>}
     * @memberof ProjectDetails
     */
    secondaryUniqueFields: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof ProjectDetails
     */
    repeatingInstruments: Array<string>;
    /**
     * @type {number}
     * @memberof ProjectDetails
     */
    nextRecordName: number;
    /**
     * @type {number}
     * @memberof ProjectDetails
     */
    hasRepeatingInstrumentsOrEvents?: number;
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    customRecordLabel?: string;
    /**
     * @type {string}
     * @memberof ProjectDetails
     */
    description?: string;
}
