/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FieldMapping,
} from './';

/**
 * @export
 * @interface ProjectMappingsReponseAllOfResult
 */
export interface ProjectMappingsReponseAllOfResult {
    /**
     * @type {number}
     * @memberof ProjectMappingsReponseAllOfResult
     */
    total: number;
    /**
     * @type {Array<FieldMapping>}
     * @memberof ProjectMappingsReponseAllOfResult
     */
    mappings: Array<FieldMapping>;
}
