/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MappingSettings,
    MergeSettings,
    ValidationSettings,
} from './';

/**
 * @export
 * @interface ProjectSettings
 */
export interface ProjectSettings {
    /**
     * @type {boolean}
     * @memberof ProjectSettings
     */
    recordAutoNumbering: boolean;
    /**
     * @type {string}
     * @memberof ProjectSettings
     */
    recordIdField: string;
    /**
     * @type {string}
     * @memberof ProjectSettings
     */
    recordIdPrefix: string;
    /**
     * @type {Array<string>}
     * @memberof ProjectSettings
     */
    repeatInstruments: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof ProjectSettings
     */
    secondaryUniqueFields: Array<string>;
    /**
     * @type {boolean}
     * @memberof ProjectSettings
     */
    confirmDeletions: boolean;
    /**
     * @type {MappingSettings}
     * @memberof ProjectSettings
     */
    mappingSettings: MappingSettings;
    /**
     * @type {ValidationSettings}
     * @memberof ProjectSettings
     */
    validationSettings: ValidationSettings;
    /**
     * @type {MergeSettings}
     * @memberof ProjectSettings
     */
    mergeSettings: MergeSettings;
}
