/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RecordValidationStatus
 */
export interface RecordValidationStatus {
    /**
     * @type {object}
     * @memberof RecordValidationStatus
     */
    workingIdentifierDict?: object;
    /**
     * @type {string}
     * @memberof RecordValidationStatus
     */
    nextSheet?: string;
    /**
     * @type {string}
     * @memberof RecordValidationStatus
     */
    nextIdentifier?: string;
    /**
     * @type {object}
     * @memberof RecordValidationStatus
     */
    nextIdentifierDict?: object;
    /**
     * @type {Array<string>}
     * @memberof RecordValidationStatus
     */
    remainingConflicts?: Array<string>;
    /**
     * @type {number}
     * @memberof RecordValidationStatus
     */
    completionProgress?: number;
}
