/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RedcapVersionPayloadPayload,
} from './';

/**
 * @export
 * @interface RedcapVersionPayload
 */
export interface RedcapVersionPayload {
    /**
     * @type {RedcapVersionPayloadPayload}
     * @memberof RedcapVersionPayload
     */
    payload: RedcapVersionPayloadPayload;
}
