/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RemoveDuplicateCorrection
 */
export interface RemoveDuplicateCorrection {
    /**
     * @type {string}
     * @memberof RemoveDuplicateCorrection
     */
    projectUid?: string;
    /**
     * @type {string}
     * @memberof RemoveDuplicateCorrection
     */
    sessionUid?: string;
    /**
     * @type {string}
     * @memberof RemoveDuplicateCorrection
     */
    sheet?: string;
    /**
     * @type {string}
     * @memberof RemoveDuplicateCorrection
     */
    identifierValue?: string;
    /**
     * @type {Array<number>}
     * @memberof RemoveDuplicateCorrection
     */
    rows?: Array<number>;
}
