/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RecordConflictTypeEnum,
} from './';

/**
 * @export
 * @interface RemoveInconsistentCorrection
 */
export interface RemoveInconsistentCorrection {
    /**
     * @type {RecordConflictTypeEnum}
     * @memberof RemoveInconsistentCorrection
     */
    conflictType?: RecordConflictTypeEnum;
    /**
     * @type {string}
     * @memberof RemoveInconsistentCorrection
     */
    projectUid?: string;
    /**
     * @type {string}
     * @memberof RemoveInconsistentCorrection
     */
    sessionUid?: string;
    /**
     * @type {string}
     * @memberof RemoveInconsistentCorrection
     */
    sheet?: string;
    /**
     * @type {string}
     * @memberof RemoveInconsistentCorrection
     */
    identifierValue?: string;
    /**
     * @type {Array<string>}
     * @memberof RemoveInconsistentCorrection
     */
    fieldName?: Array<string>;
}
