/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    RepeatingFormIdentifiers,
} from './';

/**
 * @export
 * @interface RepeatFormsResponseAllOfResult
 */
export interface RepeatFormsResponseAllOfResult {
    /**
     * @type {number}
     * @memberof RepeatFormsResponseAllOfResult
     */
    total: number;
    /**
     * @type {Array<RepeatingFormIdentifiers>}
     * @memberof RepeatFormsResponseAllOfResult
     */
    forms: Array<RepeatingFormIdentifiers>;
}
