/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LinkedFieldValue,
    NewValidationCorrection,
} from './';

/**
 * @export
 * @interface ResolveValidation
 */
export interface ResolveValidation {
    /**
     * @type {string}
     * @memberof ResolveValidation
     */
    projectUid?: string;
    /**
     * @type {string}
     * @memberof ResolveValidation
     */
    sessionUid?: string;
    /**
     * @type {string}
     * @memberof ResolveValidation
     */
    sheetName?: string;
    /**
     * @type {string}
     * @memberof ResolveValidation
     */
    fieldName?: string;
    /**
     * @type {Array<NewValidationCorrection>}
     * @memberof ResolveValidation
     */
    corrections?: Array<NewValidationCorrection>;
    /**
     * @type {Array<LinkedFieldValue>}
     * @memberof ResolveValidation
     */
    linkedValues?: Array<LinkedFieldValue>;
}
