/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ResolveMergeConflict
 */
export interface ResolveMergeConflict {
    /**
     * @type {string}
     * @memberof ResolveMergeConflict
     */
    projectUid: string;
    /**
     * @type {string}
     * @memberof ResolveMergeConflict
     */
    sessionUid: string;
    /**
     * @type {string}
     * @memberof ResolveMergeConflict
     */
    conflictUid?: string;
    /**
     * @type {string}
     * @memberof ResolveMergeConflict
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof ResolveMergeConflict
     */
    row: number;
    /**
     * @type {string}
     * @memberof ResolveMergeConflict
     */
    identifierValue: string;
    /**
     * @type {string}
     * @memberof ResolveMergeConflict
     */
    fieldName: string;
    /**
     * @type {Array<string>}
     * @memberof ResolveMergeConflict
     */
    correction: Array<string>;
}
