/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NewFieldMapping,
} from './';

/**
 * @export
 * @interface SaveMappings
 */
export interface SaveMappings {
    /**
     * @type {string}
     * @memberof SaveMappings
     */
    projectUid?: string;
    /**
     * @type {Array<NewFieldMapping>}
     * @memberof SaveMappings
     */
    newMappings?: Array<NewFieldMapping>;
}
