/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SessionValidationStatus
 */
export interface SessionValidationStatus {
    /**
     * @type {boolean}
     * @memberof SessionValidationStatus
     */
    validationComplete?: boolean;
    /**
     * @type {string}
     * @memberof SessionValidationStatus
     */
    validationCompletedOn?: string;
    /**
     * @type {boolean}
     * @memberof SessionValidationStatus
     */
    resolveComplete?: boolean;
    /**
     * @type {string}
     * @memberof SessionValidationStatus
     */
    resolveCompletedOn?: string;
}
