/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SessionMappingStatus
 */
export interface SessionMappingStatus {
    /**
     * @type {{ [key: string]: number; }}
     * @memberof SessionMappingStatus
     */
    mappedSheets?: { [key: string]: number; };
    /**
     * @type {boolean}
     * @memberof SessionMappingStatus
     */
    mappingComplete?: boolean;
    /**
     * @type {string}
     * @memberof SessionMappingStatus
     */
    mappingCompletedOn?: string;
}
