/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DataSourceSheetTypeEnum,
    DuplicateFields,
    IgnoredSourceField,
    ImportStepEnum,
    MappingSettings,
    MergeSettings,
    ProjectDetails,
    SessionMappingStatus,
    SessionValidationStatus,
    SheetIdentifiers,
    SourceDataHeader,
    ValidationSettings,
} from './';

/**
 * @export
 * @interface SessionPayload
 */
export interface SessionPayload {
    /**
     * @type {ProjectDetails}
     * @memberof SessionPayload
     */
    projectDetails?: ProjectDetails;
    /**
     * @type {ImportStepEnum}
     * @memberof SessionPayload
     */
    currentStep: ImportStepEnum;
    /**
     * @type {string}
     * @memberof SessionPayload
     */
    sourceDataName?: string;
    /**
     * @type {Array<SourceDataHeader>}
     * @memberof SessionPayload
     */
    originalDataHeaders?: Array<SourceDataHeader>;
    /**
     * @type {Array<SourceDataHeader>}
     * @memberof SessionPayload
     */
    sourceDataHeaders?: Array<SourceDataHeader>;
    /**
     * @type {Array<DuplicateFields>}
     * @memberof SessionPayload
     */
    duplicateSourceFields?: Array<DuplicateFields>;
    /**
     * @type {boolean}
     * @memberof SessionPayload
     */
    isMultiSheet?: boolean;
    /**
     * @type {DataSourceSheetTypeEnum}
     * @memberof SessionPayload
     */
    sheetType?: DataSourceSheetTypeEnum;
    /**
     * @type {string}
     * @memberof SessionPayload
     */
    sheetJoinField?: string;
    /**
     * @type {string}
     * @memberof SessionPayload
     */
    checkboxDelimiter?: string;
    /**
     * @type {boolean}
     * @memberof SessionPayload
     */
    confirmDeletions?: boolean;
    /**
     * @type {Array<IgnoredSourceField>}
     * @memberof SessionPayload
     */
    ignoredSourceFields?: Array<IgnoredSourceField>;
    /**
     * @type {Array<string>}
     * @memberof SessionPayload
     */
    malformedSheets?: Array<string>;
    /**
     * @type {Array<SheetIdentifiers>}
     * @memberof SessionPayload
     */
    sheetIdentifiers?: Array<SheetIdentifiers>;
    /**
     * @type {string}
     * @memberof SessionPayload
     */
    existingRecordsFetchedOn?: string;
    /**
     * @type {SessionMappingStatus}
     * @memberof SessionPayload
     */
    mappingStatus?: SessionMappingStatus;
    /**
     * @type {MappingSettings}
     * @memberof SessionPayload
     */
    mappingSettings?: MappingSettings;
    /**
     * @type {SessionValidationStatus}
     * @memberof SessionPayload
     */
    fieldValidationStatus?: SessionValidationStatus;
    /**
     * @type {ValidationSettings}
     * @memberof SessionPayload
     */
    fieldValidationSettings?: ValidationSettings;
    /**
     * @type {SessionValidationStatus}
     * @memberof SessionPayload
     */
    recordValidationStatus?: SessionValidationStatus;
    /**
     * @type {SessionValidationStatus}
     * @memberof SessionPayload
     */
    mergeStatus?: SessionValidationStatus;
    /**
     * @type {MergeSettings}
     * @memberof SessionPayload
     */
    mergeSettings?: MergeSettings;
}
