/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdateItem
 */
export interface UpdateItem {
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    sheet: string;
    /**
     * @type {number}
     * @memberof UpdateItem
     */
    row: number;
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    field: string;
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    identifierField: string;
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    identifier: string;
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    originalValue: string;
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    updatedValue?: string;
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    form?: string;
    /**
     * @type {string}
     * @memberof UpdateItem
     */
    instance?: string;
}
