/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UpdatedFieldValue
 */
export interface UpdatedFieldValue {
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    identifierValue: string;
    /**
     * @type {number}
     * @memberof UpdatedFieldValue
     */
    row: number;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    recordId: string;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    formName?: string;
    /**
     * @type {number}
     * @memberof UpdatedFieldValue
     */
    formInstance?: number;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    fieldName: string;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    fieldLabel?: string;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    original: string;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    originalCoded?: string;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    update: string;
    /**
     * @type {string}
     * @memberof UpdatedFieldValue
     */
    updatedCoded?: string;
}
