/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ValidationStatus
 */
export interface ValidationStatus {
    /**
     * @type {string}
     * @memberof ValidationStatus
     */
    nextSheet?: string;
    /**
     * @type {string}
     * @memberof ValidationStatus
     */
    nextField?: string;
    /**
     * @type {Array<string>}
     * @memberof ValidationStatus
     */
    remainingFields?: Array<string>;
    /**
     * @type {number}
     * @memberof ValidationStatus
     */
    completionProgress?: number;
}
