/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    FieldsWithValidationErrors,
    PvOrderingEnum,
} from './';

/**
 * @export
 * @interface ValidationSettings
 */
export interface ValidationSettings {
    /**
     * @type {boolean}
     * @memberof ValidationSettings
     */
    showPrevCorrections: boolean;
    /**
     * @type {boolean}
     * @memberof ValidationSettings
     */
    populateSuggestions: boolean;
    /**
     * @type {PvOrderingEnum}
     * @memberof ValidationSettings
     */
    pvOrdering: PvOrderingEnum;
    /**
     * @type {Array<FieldsWithValidationErrors>}
     * @memberof ValidationSettings
     */
    errorFields?: Array<FieldsWithValidationErrors>;
}
