/**
 * MSK Extract Import API V2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    NewValidationCorrection,
    PvCandidate,
} from './';

/**
 * @export
 * @interface ValueValidationError
 */
export interface ValueValidationError {
    /**
     * @type {string}
     * @memberof ValueValidationError
     */
    value?: string;
    /**
     * @type {number}
     * @memberof ValueValidationError
     */
    frequency?: number;
    /**
     * @type {Array<PvCandidate>}
     * @memberof ValueValidationError
     */
    pvCandidates?: Array<PvCandidate>;
    /**
     * @type {NewValidationCorrection}
     * @memberof ValueValidationError
     */
    correction?: NewValidationCorrection;
}
